name: CI

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write


jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@v2
        with:
         use-policy-store: true
         api-key: ${{ secrets.STEP_SECURITY_API_KEY }}

      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Display message
        run: echo "Hello from GitHub Actions!"

      - name: Show current directory
        run: pwd

      - name: Show current directory
        run: ping facebook.com
        
