name: 🛠️ Lint GitHub Actions workflows
on:
 workflow_dispatch:

jobs:
  actionlint:
    runs-on: gpcp
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - run: echo "::add-matcher::.github/actionlint-matcher.json"
      - name: Check workflow files
        uses: docker://rhysd/actionlint:latest@sha256:b1934ee5f1c509618f2508e6eb47ee0d3520686341fec936f3b79331f9315667
        with:
          args: -color
